all:
  stylesheets:  [ lib.ui-tabs ]

treeSuccess:
  stylesheets:  [ admin.pageTree ]
  javascripts:  [ lib.jstree09, admin.pageTree ]

seoSuccess:
  stylesheets:  [ admin.manualSeo ]
  javascripts:  [ admin.manualSeo ]