all:
  stylesheets:  [ lib.ui-tabs, lib.ui-accordion ]
  javascripts:  [ lib.ui-accordion ]

treeSuccess:
  stylesheets:  [ admin.pageTree ]
  javascripts:  [ lib.jstree, admin.pageTree ]

seoSuccess:
  stylesheets:  [ admin.manualSeo ]
  javascripts:  [ admin.manualSeo ]