editToggle:
  is_secure:        true
  credentials:      [tool_bar_front]

showToolBarToggle:
  is_secure:        true
  credentials:      [tool_bar_front]

toAdmin:
  is_secure:        true
  credentials:      [admin]